### ISSUE TITLE
Pretrained Model

### ISSUE THREAD

**Issue by rootally** [gautam678/Pix2Depth#17]
Hey can you upload the pretrained model for Pix2Depth?

**Comment by naavis** [comment]
Yes, that would be very useful.

**Comment by btwael** [comment]
+1

**Comment by sachinpuranik99** [comment]
+1

**Comment by gautam678** [comment]
Hey! I'm retraining the models again. I'll upload by the end of this week!

**Comment by xfarxod** [comment]
can everyone share  pretrained  model ?

**Comment by bogdan112** [comment]
Hello, there are still missing files, could you help?

**Comment by rrbarioni** [comment]
@gautam678 any updates?

**Comment by gautam678** [comment]
Hey! I'm terribly sorry, I'm caught up with work. Never got around to training the model and my weights are corrupt. I'll retrain it when I get time this winter. I'll keep this issue open.

**Comment by rrbarioni** [comment]
@gautam678 that's great! Thank you!

**Comment by maximus009** [comment]
Hey all, we would like to apologise for the delay in releasing further models and helping you all. We will Work on this and get back as soon as we can. This is definitely in our back burner and we will get around to solving this. Thank you!

**Comment by gautam678** [comment]
https://drive.google.com/drive/u/1/folders/1DzFIh9MkS-CjZYn1Mqcw1qt_0Jk9tSNe
