### ISSUE TITLE
Unable to open file in weights

### ISSUE THREAD

**Issue by hedgy123** [gautam678/Pix2Depth#19]
Hi!  I'd like to try out your code, but I am getting stuck trying to open the pix2pix_depth.h5 file in weights, with the following error:

     File "/Pix2Depth/main.py", line 27, in <module>    
       'pix2pix' : load_model('/Pix2Depth/weights/pix2pix_depth.h5')
      File "/anaconda2/envs/py27base/lib/python2.7/site-packages/keras/models.py", line 237, in   load_model
        with h5py.File(filepath, mode='r') as f:
     File "/anaconda2/envs/py27base/lib/python2.7/site-packages/h5py/_hl/files.py", line 269, in __init__
        fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
     File "/anaconda2/envs/py27base/lib/python2.7/site-packages/h5py/_hl/files.py", line 99, in make_fid
        fid = h5f.open(name, flags, fapl=fapl)
     File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
     File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
     File "h5py/h5f.pyx", line 78, in h5py.h5f.open
     IOError: Unable to open file (file signature not found)

 Any suggestions for how to fix it would be appreciated!

**Comment by divyamsaran** [comment]
@hedgy123 Were you able to fix this? I am facing the same issue.

**Comment by jiangzidong** [comment]
+1， facing the same issue

**Comment by jiangzidong** [comment]
Oh, I got the reason. The h5 file (101M) is stored by git lfs, So if you just `git clone`, it will not be downloaded. I choose to download it manully

**Comment by jiangzidong** [comment]
But the h5 file is a weight file without model information. So it will raise "ValueError: No model found in config file." when using load_model

**Comment by mrlooi** [comment]
Same issue, did you fix it?

**Comment by mrka124** [comment]
Same issue, did you fix it?

**Comment by bogdan112** [comment]
Same issue, any fixes?

**Comment by tsly123** [comment]
Hi,
I am facing the error in `main.py` :  `no module inf_cycle` ([line 12 in main.py](https://github.com/gautam678/Pix2Depth/blob/master/main.py#L12)), but I can't find the `inf_cycle` anywhere. Have you faced this error before?
Thank you,
tsly

**Comment by mrka124** [comment]
@tsly123 delete those line

**Comment by tsly123** [comment]
@kietdinh  these lines are used for `CycleGAN model` (line [46](https://github.com/gautam678/Pix2Depth/blob/master/main.py#L46) and [67](https://github.com/gautam678/Pix2Depth/blob/master/main.py#L67)) in pix2depth and depth2pix, and I intend to use the `CycleGAN model`
Do you know what is `inf_cycle` used for and how to get it?
Thanks,
tsly

**Comment by mrka124** [comment]
@tsly123 I think it use for test path? May be the author forgot commit ```inf_cycle.py``` file

**Comment by NestarZ** [comment]
@hedgy123 Check again your h5 file, it was uploaded thanks Git LFS.
Thus, you need to install Git LFS and get it using `git lfs install` or just download the raw file from github.

**Comment by ROYNITISH** [comment]
where can i download  pix2pix_depth.h5 file

**Comment by gautam678** [comment]
I've been caught up with work and didn't get to look at this repository. The models I'd trained earlier is corrupt now and I have to train the model again. I'll get down to it as soon as I get some time off from work.

**Comment by ShubhamMandwe** [comment]
@gautam678 Have you got the model trained. Please update if u did so. Thanks in anticipation.

**Comment by gautam678** [comment]
Sorry for the delay, here are the weights for pix2pix

https://drive.google.com/drive/u/1/folders/1DzFIh9MkS-CjZYn1Mqcw1qt_0Jk9tSNe
