### ISSUE TITLE
Can't access web demo

### ISSUE THREAD

**Issue by Neltherion** [gautam678/Pix2Depth#20]
Here's the error:

> 128.143.63.199 didn’t send any data.
> ERR_EMPTY_RESPONSE

**Comment by maximus009** [comment]
Yes. The demo is taken down, temporarily, as it is running on cs.virginia servers, that undergoes maintenance time to time.

**Comment by vahisht** [comment]
Is the site still undergoing maintenance? It still doesn't seem to work for me, but I'm getting ERR_CONNECTION_REFUSED when trying to connect.

```
This site can’t be reached 128.143.63.199 refused to connect.
ERR_CONNECTION_REFUSED
```
