### ISSUE TITLE
Where should I download these models?

### ISSUE THREAD

**Issue by YuehWu1994** [gautam678/Pix2Depth#22]
Hello, thanks for developing such a amazing project. I have a question that where I should download these models in main.py. You've provided links to search for 'pix2pix', 'CycleGAN' and 'CNN', but I still can't find the corresponding name in either of these links.

Thanks,

```
model_list = {  
        'pix2depth':{ 
            'pix2pix' : load_model('weights/p2d_pix2pix.h5'),
            'CycleGAN':load_model('weights/p2d_cycle.h5'),
            'CNN': load_model('weights/p2d_cnn.h5'),
            },
        'depth2pix':{ 
            'pix2pix' : load_model('weights/d2p_pix2pix.h5'),
            'CycleGAN':load_model('weights/d2p_cycle.h5'),
            }
         }
```

**Comment by shreyashk09** [comment]
where can I find model to  'pix2pix_depth.h5' weights?

**Comment by gautam678** [comment]
Hey! the weights are corrupt and I didn't have a backup. I'm planning on retraining the models this winter and publish it here. I'll keep this issue open till I upload the models back into the repo

**Comment by gautam678** [comment]
I have the models trained for pix2pix 

https://drive.google.com/drive/u/1/folders/1DzFIh9MkS-CjZYn1Mqcw1qt_0Jk9tSNe
