### ISSUE TITLE
How well does the network perform on street data?

### ISSUE THREAD

**Issue by MeghaMaheshwari** [gautam678/Pix2Depth#24]

**Comment by maximus009** [comment]
The original network was trained on indoor images. We can't say for sure how it would perform for outdoor setting.

**Comment by maximus009** [comment]
The original network was trained on indoor images. We can't say for sure how it would perform for outdoor setting.

**Comment by maximus009** [comment]
Closing this issue.
Please feel free to comment to discuss.
