### ISSUE TITLE
Web demo returns "Connection refused"

### ISSUE THREAD

**Issue by vahisht** [gautam678/Pix2Depth#25]
Whenever I try to access the link for your demo, my browser (Google Chrome, Microsoft Edge, Tor Browser) returns this error:

This site can’t be reached 
128.143.63.199 refused to connect.
ERR_CONNECTION_REFUSED

Is this on my side or yours?

Cheers!

**Comment by maximus009** [comment]
This is NOT a problem on your side.
We had hosted the app on Univ of Virginia Servers, and this was the IP serving the app.
If you are unable to connect, then the app might have been shut down/taken down when the servers restart after maintenance.
