### ISSUE TITLE
run main

### ISSUE THREAD

**Issue by wolhandlerdeb** [gautam678/Pix2Depth#26]
Hi, someone success to run the mail file
it shows to me this error:
<img width="1234" alt="capture d ecran 2018-12-09 a 12 23 27" src="https://user-images.githubusercontent.com/38043000/49696088-4af0a900-fbad-11e8-9332-8365b2b31d55.png">
If I understand correctly, i should create first or download a model.
How should I do that?
Someone did success and can help me?

Thank you very much

**Comment by gautam678** [comment]
I just updated the repository with the correct weights. I could not upload the weights on github, but you can access the weights here with some sample test images.

https://drive.google.com/drive/u/1/folders/1DzFIh9MkS-CjZYn1Mqcw1qt_0Jk9tSNe

Also make sure you have the folder /static/results created. All results get stored here

**Comment by wolhandlerdeb** [comment]
thanks a lot

Le lun. 21 janv. 2019 à 21:01, Gautam Somappa <notifications@github.com> a
écrit :

**Comment by AVCarreiro** [comment]
Hi @gautam678. I could test with the provided weights for pix2pix but the results are far from good, although this seems to be the case in the sample images you provide in the drive folder. It seems that the weights are for a weaker model, am I wrong? 

Thank you

**Comment by uros171513** [comment]
> Hi @gautam678. I could test with the provided weights for pix2pix but the results are far from good, although this seems to be the case in the sample images you provide in the drive folder. It seems that the weights are for a weaker model, am I wrong?
> Thank you

Hi @AVCarreiro, I faced with the same issue, the results aren't quite good (for both sample images and my images), did you figure it out what's the problem?

**Comment by AVCarreiro** [comment]
Not really, my guess is that the trained model is not the best one. Tried using other weights (instead of the whole saved model) the author shared but then I need to know model parameters in order to load it...
