### ISSUE TITLE
Train models

### ISSUE THREAD

**Issue by AVCarreiro** [gautam678/Pix2Depth#27]
Hello, first of all thanks for sharing this repository.

Because the weights are corrupt, I was trying to train the models, so I went through the code but it seems the actual models file (with model definitions and loading) is missing. Will you share this? 

Thank you

**Comment by gautam678** [comment]
I just updated the repository with the correct weights. I could not upload the weights on github, but you can access the weights here with some sample test images.

https://drive.google.com/drive/u/1/folders/1DzFIh9MkS-CjZYn1Mqcw1qt_0Jk9tSNe
