### ISSUE TITLE
Pretrain Model for CycleGAN

### ISSUE THREAD

**Issue by akamob** [gautam678/Pix2Depth#34]
Hi, Thank you for the great work.

I'm wondering if it is possible that you could share the pretrain model for CycleGAN with .pth format? Due to the limited computational power, I can only train the model on Colab (it only accepts .pth files).

Any help is much appreciated:)

**Comment by maximus009** [comment]
Hi @akamob , we have shared the weights file to the models that we trained - please refer to the readme.
Also, just FYI, we built this on Keras, not Pytorch.

Thanks! :)

**Comment by akamob** [comment]
Thank you for your reply:) I'll go ahead and have a try.
